### PR TITLE
Browser Support

### LINKED ISSUE #18: Browser-Support
Check if it works in browsers.

### PR DESCRIPTION
**Pull request by aurium**
closes #18
total remove util dependency also its shim. closes #20

`util` shim is not needed anymore.
browser tests now works.

### CODE REVIEW

**Comment by pvorb** [comment]
While I appreciate your work, I can't accept this pull request, because of this [article about `instanceof`](http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/).

Why do you think the util shim is bad?

**Comment by aurium** [comment]
Hey, thanks by the advise @pvorb!

I'll rewrite with a duck-typing test method to replace `instanceof` tests.

About the *util shim*, i see it needs a very small subset of this module *(reduced only to `getRegExpFlags`, and that is not from `util`)*, and the "cloned" methods must work as the same everywhere to simply tests and consistent behavior. So, why to use one implementation in node and other in other environments? I believe that is simpler (or better) use only an internal implementation. Is this ok for you or did i missed something?

**Comment by aurium** [comment]
Plus:
* I did put all helper methods inside `clone` namespace to do not conflict with a possible user implementation of `isArray` and other methods, but also still easy to test it.
* There is a nice test helper apartContext, that creates a new VM on node and iFrame on browsers.
* More tests to ensure `is*`

**Comment by pvorb** [comment]
This looks way better, but I think those helper methods shouldn't be members of `clone` in order to prevent users to use and rely on them.

Probably we should wrap it in a separate function.

~~~ js
(function(){ /* clone's code */ })();
~~~

**Comment by aurium** [comment]
Yes, i think in use a closure, but it makes harder to test the helpers... I did consider to use [Philip Walton's approach](http://philipwalton.com/articles/how-to-unit-test-private-functions-in-javascript), but i will try to keep it simple.

**Comment by aurium** [comment]
What? Travis removed nodeunit? [`sh: 1: nodeunit: not found`](https://travis-ci.org/pvorb/node-clone/jobs/47003285)

**Comment by aurium** [comment]
@pvorb, i believe Travis had a problem with nodeunit. Can you teste it locally?

**Comment by pvorb** [comment]
@aurium Sorry, I'm busy this week. I'll try to it next week.

**Comment by aurium** [comment]
Ok! Don't worry.

**Pull request merged**
