### PR TITLE
fix lint issues

### PR DESCRIPTION
**Pull request by fscherwi**

### CODE REVIEW

**Comment by pvorb** [comment]
Thank you for your contributions. Can you please try to make all tests pass?

**Comment by fscherwi** [comment]
Yet there are all builds passing!

**Comment by pvorb** [comment]
Thanks.

**Comment by fscherwi** [comment]
No Problem!

**Comment by pvorb** [comment]
If you don't mind I'll add you to the list of contributors in `package.json`.

**Comment by fscherwi** [comment]
Yes, please!

**Pull request merged**
