### PR TITLE
Hid Buffer from browserify, reduces browserified size by 40KB

### PR DESCRIPTION
**Pull request by KoryNunn**
Because browserify looks for a `Buffer` identifier in the source and then assumes it is required, and bundles it in, just requiring clone causes it to be added.

This change hides Buffer from browserify, but still allows code that needs Buffer to work, both on the client and in node.

### CODE REVIEW

**Comment by KoryNunn** [comment]
Also, I'm trying to make this cleaner with this issue: https://github.com/substack/node-browserify/issues/1228

**Comment by pvorb** [comment]
Why do you need this, when there's the possibility to use `noParse: ['clone']` like @zertosh stated?

BTW: You shouldn't add a npm-debug.log into your pull requests.

**Comment by KoryNunn** [comment]
debug log removed.

I actually *dont* think this pull request is the best solution, as mentioned in the browserify issue, but it does work in the meantime.

If there is any intent to add support for a flag per module in browserify, this shouldn't be merged.

However, if it isn't added, this is the only way around the issue that doesn't require developers to know that this module contains the identifier `Buffer`, and to always run `noParse: ['clone']`.

I'm not sure how manually adding a noParse flag to every clientside project that has clone anywhere in its dependency tree could be considered a good idea.

**Comment by KoryNunn** [comment]
After digging into how browserify adds things to scope I've realised that this wont work how I expected. There is currently no way for a module to say that it *can* deal with a built-in without that module causing the built-in to be bundled.

**Comment by feross** [comment]
Hey guys, you might consider using my package [`is-buffer`] that is specifically designed to address this use case. To quote the readme:

> This module lets you check if an object is a Buffer without using Buffer.isBuffer (which includes the whole buffer module in browserify). It's future-proof and works in node too!

Enjoy!

**Comment by feross** [comment]
Link here: https://www.npmjs.com/package/is-buffer

**Pull request closed without merging**
